# A test configuration file
hostname: gps

devices:
- devicemodulename: serial_device
  deviceconfig:
    name: serial
    serial_name: /dev/ttyUSB1
    baud: 4800
- devicemodulename: gps_device
  deviceconfig:
    name: gps

- devicemodulename: network_device  
  deviceconfig:
    name: tcp
    config:
       address: <ip> # Address IP, localhost. <broadcast> for UDP broadcast in local network. <ip> for local ip
       port: 10001
       serialize: str # yaml,str default yaml
       protocol: tcp # tcp, udp default tcp
       direction: publish # publish, receive default receive
       data: nmea # dictionary keys, default all

- devicemodulename: netcdflogger  
  deviceconfig:
    name: nclog
    config:
      filename: 'gps1.nc'
      zlib: True
      dt_newfile: 3600
      groups:
        - name: "gps@gps" # Creates a group redvyprrand1 and adds automatic variables of all devices received         


connections:
- publish: serial
  receive: gps
- publish: gps
  receive: nclog
- publish: gps
  receive: tcp
  
  
start:
- serial
- gps
- tcp

