# A test configuration file
hostname: plotdata

devices:
- deviceconfig:
    name: udp
    loglevel: info
    config:
      address: <broadcast>
      port: 18196
      protocol: udp
      direction: receive
  devicemodulename: network_device    
# Plot the data
- deviceconfig: # The plotting device
    name: plot
    config:
       - title: Plot A
         type: graph
         location: [0,0] # The location as in QgridBoxLayout
         xlabel: time
         ylabel: Voltage
         datetick: True
         lines: 
            - device: rand1@redvyprrand1
              name: rand1@redvyprrand1
              x: t
              y: data
              linewidth: 2
              color: [0,255,0]
              buffersize: 200
            - device: rand4@redvyprrand2
              name: rand1@redvyprrand2
              x: t
              y: data
              linewidth: 2
              color: [255,0,0]
              buffersize: 200

       - title: Plot B
         type: graph
         location: [0,1] # The location as in QgridBoxLayout
         xlabel: time
         ylabel: Voltage
         datetick: True
         lines: 
            - device: rand1@redvyprrand2
              name: rand1@redvyprrand1
              x: t
              y: data
              linewidth: 2
              color: [0,255,0]
              buffersize: 200

       - title: Some data
         type: numdisp
         location: [1,1] # The location as in QgridBoxLayout
         device: rand3@redvyprrand1
         devicelabel: False
         data: data
         unit: rand. unit
         dataformat: +3.1f
         
  devicemodulename: plot
- deviceconfig:
    name: nc
    config:
      filename: 'randdata_test.nc'
      zlib: True
      dt_newfile: 360
      file_timestamp: True      
      attributes: # Add attributes to the variables
      - name: 'experiment'
        value: 'Multiple data streams into one netCDF file' 
      groups:
        - name: randdata
          devices:
            - rand1@redvyprrand1
          variables:
            - name: rand1
              key: data
              type: float
              attributes: # Add attributes to the variables
              - name: 'long_name'
                value: 'Random data'
              
  devicemodulename: netcdflogger  
  
connections:
- publish: udp
  receive: plot
- publish: udp
  receive: nc

  
  
start:
- udp
- plot
- nc
