# A test configuration file
hostname: plotdata

devices:
- deviceconfig:
    name: udp
    loglevel: info
    config:
      address: <broadcast>
      port: 18196
      protocol: udp
      direction: receive
  devicemodulename: network_device    
# Plot the data
- deviceconfig: # The plotting device
    name: plot
    config:
       - title: Plot A
         type: graph
         location: [0,0] # The location as in QGridBoxLayout
         xlabel: time
         ylabel: Voltage [V]
         datetick: True
         lines:
            - device: sinrandfast@*
              name: sinrandfast@*
              x: t
              y: data
              linewidth: 2
              color: [0,255,0]
              buffersize: 200
            - device: sinn@*
              x: t
              y: data
              linewidth: 2
              color: [255,0,0]
              buffersize: 1000

       - title: Plot B
         type: graph
         location: [0,1] # The location as in QgridBoxLayout
         useprops: True
         xlabel: time
         datetick: True
         lines: 
            - device: sinrandfast@*
              x: t
              y: data
              linewidth: 2
              color: [0,255,0]
              buffersize: 1000

       - title: Some data
         type: numdisp
         location: [1,0] # The location as in QgridBoxLayout
         device: count@r1
         useprops: True
         data: data
         dataformat: +3.1f
         
       - title: Some data 2
         type: numdisp
         location: [1,1] # The location as in QgridBoxLayout
         device: sinn@*
         useprops: True
         data: data
         dataformat: +3.1f         
         
  devicemodulename: plot
# NetCDF logger
- deviceconfig:
    name: nc
    config:
      mp: process
      filename: 'randdata_udp.nc'
      zlib: True
      dt_newfile: 3600
      file_timestamp: True      
      attributes: # Add attributes to the variables
      - name: 'experiment'
        value: 'Multiple data streams into one netCDF file' 
      groups:
        - name: "*@*" # Creates a group redvyprrand1 and adds automatic variables of all devices received 

  devicemodulename: netcdflogger
  
connections:
- publish: udp
  receive: plot
- publish: udp
  receive: nc

  
  
start:
- udp
- plot
- nc
