# A test configuration file
hostname: redvyprrand1

devices:
- deviceconfig:
    name: rand1
    loglevel: info
    config:
      dt: .5
      functions:
        - name: sin
          f: 0.05
          amp: 25
          phase: 0      
  devicemodulename: randdata
- deviceconfig:
    name: rand2
    loglevel: info
    config:
      dt: .5
      functions:
        - name: count
          count: 0.1
  devicemodulename: randdata
- deviceconfig:
    name: rand3
    loglevel: info
    config:
      dt: .5
      functions:
        - name: rand
          range: [-1,1]
  devicemodulename: randdata
- deviceconfig:
    name: rand4
    loglevel: info
    config:
      dt: .5
      functions:
        - name: sin
          f: 0.01
          amp: 2
          phase: 0              
        - name: rand
          range: [-1,1]
  devicemodulename: randdata
- deviceconfig:
    name: rand5
    loglevel: info
    config:
      dt: .5
      functions:
        - name: count
          count: 0.1 
        - name: rand
          range: [-1,1]
  devicemodulename: randdata
  
- deviceconfig:
    name: udp
    loglevel: info
    config:
      address: <broadcast>
      port: 18196
      protocol: udp
      direction: publish
  devicemodulename: network_device  

connections:
- publish: rand1
  receive: udp
- publish: rand2
  receive: udp
- publish: rand3
  receive: udp
- publish: rand4
  receive: udp
- publish: rand5
  receive: udp          
  
start:
- rand1
- rand2
- rand3
- rand4
- rand5
- udp
