# A test configuration file
hostname: redvyprrand1

devices:
- deviceconfig:
    name: sin
    loglevel: info
    config:
      dt: .5
      functions:
        - name: sin
          f: 0.05
          amp: 25
          phase: 0      
  devicemodulename: randdata
- deviceconfig:
    name: count
    loglevel: info
    config:
      dt: .5
      functions:
        - name: count
          count: 0.1
  devicemodulename: randdata
- deviceconfig:
    name: sinrand
    loglevel: info
    config:
      dt: .5
      functions:
        - name: sin
          f: 0.01
          amp: 2
          phase: 0              
        - name: rand
          range: [-1,1]
  devicemodulename: randdata
- deviceconfig:
    name: sincount
    loglevel: info
    config:
      dt: .5
      functions:
        - name: count
          count: 0.1 
        - name: rand
          range: [-1,1]
  devicemodulename: randdata
  
- deviceconfig:
    name: udp
    loglevel: info
    config:
      address: <broadcast>
      port: 18196
      protocol: udp
      direction: publish
  devicemodulename: network_device  

connections:
- publish: sin
  receive: udp
- publish: count
  receive: udp
- publish: sinrand
  receive: udp
- publish: sincount
  receive: udp          
  
start:
- sin
- count
- sinrand
- sincount
- udp
